### ISSUE TITLE
missing main.js

### ISSUE THREAD

**Issue by AJM38** [EthanGreen-sol/Sniper-Calls-Bot#1]
![CMD](https://github.com/user-attachments/assets/c25af371-d467-4ab1-bece-523ad7a46b57)
![web](https://github.com/user-attachments/assets/405b2f99-6438-4c75-8e1f-4e2a69b53675)

What steps should be taken to ensure that the main.js file is properly generated and available in the /dist/ directory?

**Comment by EthanGreen-sol** [comment]
Hello, dear user. Please install version v1.0.1, which was just released. In v1.0.1 this problem is solved.
